//-------------ACCOUNTS--------------

// ACCOUNTS
// Will be posted from Add Account Component, but here is a sample object of account table

// {
// account_id: "0",
// platform: "instagram",
// username: "testusername",
// password: "testpassword",
// active: "pending",
// beta: false,
// checkpoint_method: "email",
// last_start: "",
// initial_date: "",
// initial_following_count: "",
// initial_follower_count: "",
// initial_media_count: "",
// initial_affinity: "",
// initial_affinity_mean: "",
// initial_affinity_cardinality: "",
// initial_affinity_min: "",
// initial_affinity_max: ""
//  }

//ADD CONSTRAINTS
//alter table accounts drop constraint "accounts_pkey", add primary key(username, platform, email);

//-----------------INTERACTIONS------------------

// INTERACTIONS columns
// version
// cut_point_follow_max,
// cut_point_follow_min,
// cut_point_follow_ratio,
// blacklist,
// blacklist_tags,
// blacklist_usernames,
// force_unfollow,
// like_from_discover,
// max_like_for_one_tag,
// like_per_day,
// follow_per_day,
// unfollow_per_day,
// comments_per_day,
// media_max_like,
// media_min_like,
// media_min_interest,
// follow_and_like_max,
// max_target_followers,
// min_target_followers,
// min_media_follow,
// min_affinity,
// start_date,
// end_date,
// accountAccountId

//  INTERACTION DEFAULT SETTINGS
  // version: 'string'
  // cut_point_follow_max: 7500,
  // cut_point_follow_min: 1000,
  // cut_point_follow_ratio: 1.5,
  // blacklist: {},
  // blacklist_tags: [
  //   "second",
  //   "stuff",
  //   "project",
  //   "love",
  //   "life",
  //   "food",
  //   "blog",
  //   "free",
  //   "keren",
  //   "indo",
  //   "shop",
  //   "store",
  //   "sex",
  //   "toko",
  //   "jual",
  //   "online",
  //   "murah",
  //   "jam",
  //   "kaos",
  //   "case",
  //   "baju",
  //   "fashion",
  //   "hair",
  //   "corp",
  //   "tas",
  //   "butik",
  //   "grosir",
  //   "karpet",
  //   "sosis",
  //   "salon",
  //   "skin",
  //   "care",
  //   "cloth",
  //   "tech",
  //   "rental",
  //   "kamera",
  //   "beauty",
  //   "express",
  //   "kredit",
  //   "collection",
  //   "impor",
  //   "preloved",
  //   "follow",
  //   "follower",
  //   "gain",
  //   ".id",
  //   "_id",
  //   "bags",
  //   "repost",
  //   "pink",
  //   "transformation",
  //   "instagram",
  //   "facebook",
  //   "follow",
  //   "men",
  //   "sex",
  //   "babes",
  //   "like",
  //   "quote",
  //   "quotes",
  //   "dailyquote",
  //   "baby",
  //   "babies",
  //   "cat",
  //   "cats",
  //   "mom",
  //   "gains",
  //   "gainz",
  //   "workout",
  //   "gymrat",
  //   "lift",
  //   "business",
  //   "startup",
  //   "free",
  //   "giveaway",
  //   "me",
  //   "quoteoftheday",
  //   "promote",
  //   "rental",
  //   "goals",
  //   "networking",
  //   "motivated",
  //   "motivation",
  //   "learn",
  //   "blogger",
  //   "blog",
  //   "fblogger",
  //   "gym",
  //   "fittness",
  //   "sexy",
  //   "healthy",
  //   "work",
  //   "tag",
  //   "tags4likes",
  //   "tags4like",
  //   "f4f",
  //   "l4l",
  //   "wealth",
  //   "follow4follow"
  // ],
  // blacklist_usernames: [
  //   "second",
  //   "stuff",
  //   "project",
  //   "love",
  //   "life",
  //   "food",
  //   "blog",
  //   "free",
  //   "keren",
  //   "indo",
  //   "shop",
  //   "store",
  //   "sex",
  //   "toko",
  //   "jual",
  //   "online",
  //   "murah",
  //   "jam",
  //   "kaos",
  //   "case",
  //   "baju",
  //   "fashion",
  //   "hair",
  //   "corp",
  //   "tas",
  //   "butik",
  //   "grosir",
  //   "karpet",
  //   "sosis",
  //   "salon",
  //   "skin",
  //   "care",
  //   "cloth",
  //   "tech",
  //   "rental",
  //   "kamera",
  //   "beauty",
  //   "express",
  //   "kredit",
  //   "collection",
  //   "impor",
  //   "preloved",
  //   "follow",
  //   "follower",
  //   "gain",
  //   ".id",
  //   "_id",
  //   "bags"
  // ],
  // force_unfollow: false,
  // like_from_discover: false,
  // max_like_for_one_tag: 5,
  // like_per_day: 1000,
  // follow_per_day: 800,
  // unfollow_per_day: 800,
  // comments_per_day: 0,
  // media_max_like: 50,
  // media_min_like: 0,
  // media_min_interest: 0,
  // follow_and_like_max: 7,
  // max_target_followers: 50000,
  // min_target_followers: 60,
  // min_media_follow: 5,
  // min_affinity: 0,
  // start_date: "",
  // end_date: "",
  // created_at: '',
  // updated_at: '',
  // accountAccountId: '0'
// };

//THIS COMMAND ADDS THE DEFAULT CONFIG DATA CSV DATA TO POSTGRES CONFIG_INTERACTIONS
//psql -d gyfanbase --user=katiemcculloch -c "COPY config_interactions(version, cut_point_follow_max,cut_point_follow_min,cut_point_follow_ratio,blacklist,blacklist_tags,blacklist_usernames,force_unfollow,like_from_discover,max_like_for_one_tag,like_per_day,follow_per_day,unfollow_per_day,comments_per_day,media_max_like,media_min_like,media_min_interest,follow_and_like_max,max_target_followers,min_target_followers,min_media_follow,min_affinity,start_date,end_date) FROM '/Users/katiemcculloch/hrla24/GYFanbase/database/defaultConfigData.csv' CSV;"

//THIS COMMAND DOWNLOADS CSV OF ALL CONFIG_INTERACTIONS
//\copy (select * from config_interactions) TO '~/Downloads/gynbase.csv' CSV HEADER

//-------------TARGETING--------------

// var config_targeting_default = {
// users: [],
// locations: [],
// gender: 0.5,
// tags: ["photography", "travel"],
// rolling_tags: false,
// allow_personal_accounts: true,
// allow_business_accounts: true,
// allow_private_accounts: true,
// affinity_targeting: [],
// pool_targets: false,
// pool_name: "*",
// pool_to_discover_ratio: 2,
// target_class: 0,
// account_id
// }

//-------------RUNTIME--------------

// var config_runtime_default = {
// 	"log_level": 10,
// 	"log_mod": 1,
// 	"proxy": true,
//   "proxy_zone": "static",
//   "roll_count": 1,
//   "min_follow_size": 50,
//   "min_inspect_size": 50,
//   "min_target_pool_size": 0,
//   "min_unfollow_size": 50,
//   "cycle_element_limit": 30,
//   "timeout": 48,
//   "timeout_cycle_all": 3600,
// 	"timeout_cycle_expired": 300,
// 	"timeout_cycle_pending": 900,
// 	"timeout_cycle_self": 60,
// 	"timeout_discover": 60,
// 	"timeout_inspect": 60,
// 	"timeout_print_summary": 5,
// 	"timeout_process_feed": 150,
// 	"timeout_update_preferences": 7200,
// 	"backoff_inspect": 1
// }
